import logging
import traceback

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

# main.py
from core.exceptions import AppException
from services.ai_service import AIService

# ==========================================
# 1. DATABASE & MODEL IMPORTS
# ==========================================
from db.base import Base
from db.models import user, classroom, student, student_score, skill
from db.models.skill import SkillModel   

from db.session import engine

# ==========================================
# 2. ROUTER IMPORTS
# ==========================================
from api import (auth, classrooms, students, student_scores, setup, grading) 

# Configure logging for stdout / Docker logs
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - [%(levelname)s] - %(message)s"
)
logger = logging.getLogger("uvicorn.error")

# Initialize database tables (MVP approach)
Base.metadata.create_all(bind=engine)

app = FastAPI(
    title="Ielts exam api",
    description="Whatever",
    version="2.0.0"
)

app.include_router(auth.router, prefix="/api/auth", tags=["Authentication"])  
app.include_router(classrooms.router, prefix="/api/classrooms", tags=["Classrooms"])
app.include_router(students.router, prefix="/api/students", tags=["Students"])
app.include_router(student_scores.router, prefix="/api/student-scores", tags=["Student Scores"])
app.include_router(grading.router, prefix="/api/grading", tags=["Grading"])
app.include_router(setup.router, prefix="/api/setup", tags=["System Setup"]) 


# 🟢 AUTOMATIC INTERCEPTOR: Catches any AppException raised anywhere in your app
@app.exception_handler(AppException)
async def automatic_ai_exception_handler(request: Request, exc: AppException):
    """
    Runs automatically whenever 'raise AppException' (or any subclass) occurs.
    """
    # 1. Build a fallback explanation in case AI is offline
    ai_explanation = "Please review system logs for full details."
    error = None 
    
    # 2. Pass the caught exception's message automatically to Gemini
    try:
        ai_service = AIService()
        ai_analysis = ai_service.generate_smart_error_payload(
            error_context=f"Route: {request.url.path} | Error: {exc.message} | Payload: {exc.payload}"
        )
        ai_explanation = ai_analysis.suggested_fix
    except Exception as ai_err:
        error = f"AI service failed: {str(ai_err)}"

    # 3. Return response with original error + AI explanation
    return JSONResponse(
        status_code=exc.status_code,
        content={
            "message": exc.message,  
            "payload": exc.payload,
            "ai_suggestion": ai_explanation,
            'error': error  # 🟢 Auto-generated by Gemini
        }
    )     


# 🔴 GLOBAL EXCEPTION HANDLER: Catches unhandled crashes (500 Internal Server Error)
@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    """
    Catches any unexpected Python crash, logs full traceback to stdout (Docker logs),
    and returns a clean JSON error response.
    """
    error_traceback = traceback.format_exc()
    logger.error(
        f"\n💥 [INTERNAL SERVER ERROR 500]\n"
        f"Route: {request.method} {request.url.path}\n"
        f"Traceback:\n{error_traceback}"
    )
    return JSONResponse(
        status_code=500,
        content={
            "message": "An unexpected internal server error occurred.",
            "detail": str(exc)
        }
    )