import logging
import os
import traceback
from datetime import datetime, timezone

from fastapi import APIRouter, FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

# main.py
from core.exceptions import AppException
from services.ai_service import AIService

'''from core.exceptions import AppException
# 🟢 IMPORT REUSABLE REDIS CLIENT (From core/redis.py)
from core.redis import redis_client'''

# ==========================================
# 1. DATABASE & MODEL IMPORTS
# ==========================================
from db.base import Base
from db.models import (user, student, classroom, skill, student_score)
from db.session import engine

# ==========================================
# 2. ROUTER IMPORTS
# ==========================================
from api import (auth, deps, classrooms) 

# Initialize database tables (MVP approach)
Base.metadata.create_all(bind=engine)

app = FastAPI(
    title="Ielts exam api",
    description="Whatever",
    version="2.0.0")


app.include_router(auth.router, prefix="/api/auth", tags=["Authentication"])  
app.include_router(classrooms.router, prefix="/api/classrooms", tags=["Classrooms"])








# 🟢 AUTOMATIC INTERCEPTOR: Catches any AppException raised anywhere in your app
@app.exception_handler(AppException)
async def automatic_ai_exception_handler(request: Request, exc: AppException):
    """
    Runs automatically whenever 'raise AppException' (or any subclass) occurs.
    """
    # 1. Build a fallback explanation in case AI is offline
    ai_explanation = "Please review system logs for full details."
    
    # 2. Pass the caught exception's message automatically to Gemini
    try:
        ai_service = AIService()
        ai_analysis = ai_service.generate_smart_error_payload(
            error_context=f"Route: {request.url.path} | Error: {exc.message} | Payload: {exc.payload}"
        )
        ai_explanation = ai_analysis.suggested_fix
    except Exception as ai_err:
        print(f"⚠️ Could not reach Gemini AI: {ai_err}")

    # 3. Return response with original error + AI explanation
    return JSONResponse(
        status_code=exc.status_code,
        content={
            "message": exc.message,
            "payload": exc.payload,
            "ai_suggestion": ai_explanation  # 🟢 Auto-generated by Gemini
        }
    )     